"""empty message

Revision ID: 26fc5b41c058
Revises: b32bcaa9792b
Create Date: 2022-10-26 22:12:28.258744

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '26fc5b41c058'
down_revision = 'b32bcaa9792b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expense', 'total')
    op.add_column('profiles', sa.Column('name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'name')
    op.add_column('expense', sa.Column('total', sa.NUMERIC(precision=14, scale=2), nullable=True))
    # ### end Alembic commands ###
