"""empty message

Revision ID: b32bcaa9792b
Revises: cea149fbd50e
Create Date: 2022-10-19 01:26:35.706326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b32bcaa9792b'
down_revision = 'cea149fbd50e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expense', 'total')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense', sa.Column('total', sa.NUMERIC(precision=14, scale=2), nullable=True))
    # ### end Alembic commands ###
